name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: make build-cross-static

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Compress
        run: |
          pwd
          zip --junk-paths nukibridgectl-${{ steps.get_version.outputs.VERSION }}-darwin.zip nukibridgectl-darwin-amd64-static
          file nukibridgectl-${{ steps.get_version.outputs.VERSION }}-darwin.zip
          zip --junk-paths nukibridgectl-${{ steps.get_version.outputs.VERSION }}-linux nukibridgectl-linux-amd64-static
          file nukibridgectl-${{ steps.get_version.outputs.VERSION }}-linux.zip
          zip --junk-paths nukibridgectl-${{ steps.get_version.outputs.VERSION }}-windows nukibridgectl-windows-amd64-static
          file nukibridgectl-${{ steps.get_version.outputs.VERSION }}-windows.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Darwin
        id: upload_darwin_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: nukibridgectl-${{ steps.get_version.outputs.VERSION }}-darwin.zip
          asset_name: nukibridgectl-${{ steps.get_version.outputs.VERSION }}-darwin.zip
          asset_content_type: application/zip

      - name: Upload Linux
        id: upload_linux_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: nukibridgectl-${{ steps.get_version.outputs.VERSION }}-linux.zip
          asset_name: nukibridgectl-${{ steps.get_version.outputs.VERSION }}-linux.zip
          asset_content_type: application/zip

      - name: Upload Windows
        id: upload_windows_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: nukibridgectl-${{ steps.get_version.outputs.VERSION }}-windows.zip
          asset_name: nukibridgectl-${{ steps.get_version.outputs.VERSION }}-windows.zip
          asset_content_type: application/zip
